### ISSUE TITLE
setClipboard function not work and also i cant buy item from roblox!

### ISSUE THREAD

**Issue by Eskeyz** [NotExcelz/LInjector#8]
when i use remote spy and want to copy code, the code didn't copy on my clipboard, and when i want to buy gamepass, the ui dissapear

**Comment by NotExcelz** [comment]
setclipboard works pretty nice what in the world are you saying

**Comment by Eskeyz** [comment]
> setclipboard works pretty nice what in the world are you saying

nvm, wrong repo hehe. But why Flux API setclipboard not supported ?

**Comment by NotExcelz** [comment]
No, FluxAPI doesn't haves custom functions.

**Comment by Eskeyz** [comment]
> No, FluxAPI doesn't haves custom functions.

alr, thanks for answer
